print('hello world')
atef elmla7

        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_159.setFont(font)
        self.pushButton_159.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_159.setObjectName("pushButton_159")
        self.lineEdit_135 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_135.setGeometry(QtCore.QRect(990, 220, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_135.setFont(font)
        self.lineEdit_135.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_135.setObjectName("lineEdit_135")
        self.lineEdit_133 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_133.setGeometry(QtCore.QRect(20, 140, 421, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_133.setFont(font)
        self.lineEdit_133.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_133.setObjectName("lineEdit_133")
        self.label_322 = QtWidgets.QLabel(self.centralwidget)
        self.label_322.setGeometry(QtCore.QRect(1300, 180, 136, 33))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_322.setFself.lineEdit_133.setFont(font)
        self.lineEdit_133.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_133.setObjectName("lineEdit_133")
        self.label_322 = QtWidgets.QLabel(self.centralwidget)
        self.label_322.setGeometry(QtCore.QRect(1300, 180, 136, 33))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_322.setF
           font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_159.setFont(font)
        self.pushButton_159.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_159.setObjectName("pushButton_159")
        self.lineEdit_135 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_135.setGeometry(QtCore.QRect(990, 220, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_135.setFont(font)
        self.lineEdit_135.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_135.setObjectName("lineEdit_135")
        self.l